CaseStudyMVC/Models/ErrorViewModel.cs
namespace CaseStudyMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CaseStudyMVC/Controllers/AccountsController.cs
using CaseStudyMVC.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using WebClassLibrary;

namespace CaseStudyMVC.Controllers
{
    public class AccountsController : Controller
    {
        private readonly IAuthenticationService _authService;
        public AccountsController(IAuthenticationService authService)
        {
            _authService = authService;
        }

        [HttpGet]
        public IActionResult Login()
        {
            var model = new AuthenticationRequest();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Login(AuthenticationRequest model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var authResponse = await _authService.Authenticate(model);
            if (authResponse == null)
            {
                ModelState.AddModelError("", "Bad Username/Password.");
                return View(model);
            }
            HttpContext.Session.SetString("Token", authResponse.Token);
            
            HttpContext.Session.SetInt32("UserId", authResponse.UserId);
            var user = await _authService.GetUserModel(authResponse.UserId, authResponse.Token);
            if (user != null)
            {
                var str = ConvertData.ObjectToJsonString(user);
                HttpContext.Session.SetString("User", str);
            }
            return RedirectToAction(actionName: "Index", controllerName: "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

CaseStudyMVC/Controllers/HomeController.cs
using CaseStudyMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CaseStudyMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CaseStudyMVC/Controllers/RoleController.cs
using CaseStudy1.DataAccess.Repositories;
using CaseStudy1.DataAccess;
using CaseStudyMVC.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace CaseStudyMVC.Controllers
{
    public class RoleController : Controller
    {
        private readonly IRepositoryAsync<Role> _repositoryAsync;
        private readonly ApiConfigurations _apiConfig;
        public RoleController(
            IRepositoryAsync<Role> repositoryAsync,
            IOptions<ApiConfigurations> options)
        {
            _repositoryAsync = repositoryAsync;
            _apiConfig = options.Value;
        }

        [TokenCheck]
        public async Task<IActionResult> List()
        {
            var model = await _repositoryAsync.GetAll();
            return View(model);
        }

        [TokenCheck]
        public async Task<IActionResult> Details(int id)
        {
            var model = await _repositoryAsync.GetById(id);
            return View(model);
        }

        [HttpGet]
        [TokenCheck]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [TokenCheck]
        public async Task<IActionResult> Create(Role role)
        {
            await _repositoryAsync.CreateNew(role);
            return RedirectToAction("List");
        }

        [HttpGet]
        [TokenCheck]
        public async Task<IActionResult> Remove(int id)
        {
            var model = await _repositoryAsync.GetById(id);
            if (model == null)
            {
                return RedirectToAction("List");
            }
            return View(model);
        }

        [ActionName("Remove")]
        [HttpPost]
        [TokenCheck]
        public async Task<IActionResult> RemoveConfirmed(int id)
        {
            await _repositoryAsync.Remove(id);
            return RedirectToAction("List");
        }

        [HttpGet]
        [TokenCheck]
        public async Task<IActionResult> Edit()
        {
            
            return View();
        }

        //[HttpPut]
        [TokenCheck]
        public async Task<IActionResult> Edit(Role role)
        {
            await _repositoryAsync.Update(role);
            return RedirectToAction("List");
        }
    }
}

CaseStudyMVC/Controllers/UserController.cs
using CaseStudy1.DataAccess;
using CaseStudy1.DataAccess.Repositories;
using CaseStudyMVC.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using NuGet.Protocol.Core.Types;
using UserRoleProcess;

namespace CaseStudyMVC.Controllers
{
    public class UserController : Controller
    {
        private readonly IRepositoryAsync<User> _repositoryAsync;
        private readonly ApiConfigurations _apiConfig;
        public UserController(
            IRepositoryAsync<User> repositoryAsync,
            IOptions<ApiConfigurations> options)
        {
            _repositoryAsync = repositoryAsync;
            _apiConfig = options.Value;
        }

        [TokenCheck]
        public async Task<IActionResult> List()
        {
            var model = await _repositoryAsync.GetAll();
            return View(model);
        }

        [TokenCheck]
        public async Task<IActionResult> Details(int id)
        {
            var model = await _repositoryAsync.GetById(id);
            return View(model);
        }

        [HttpGet]
        [TokenCheck]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [TokenCheck]
        public async Task<IActionResult> Create(User user)
        {
            await _repositoryAsync.CreateNew(user);
            return RedirectToAction("List"); 
        }

        [HttpGet]
        [TokenCheck]
        public async Task<IActionResult> Remove(int id)
        {
            var model = await _repositoryAsync.GetById(id);
            if (model == null)
            {
                return RedirectToAction("List");
            }
            return View(model);
        }

        [ActionName("Remove")]
        [HttpPost]
        [TokenCheck]
        public async Task<IActionResult> RemoveConfirmed(int id)
        {
            await _repositoryAsync.Remove(id);
            return RedirectToAction("List");
        }

        [HttpGet]
        [TokenCheck]
        public async Task<IActionResult> Edit()
        {
            return View();
        }

        //[HttpPut]
        [TokenCheck]
        public async Task<IActionResult> Edit(User user)
        {
            await _repositoryAsync.Update(user);
            return RedirectToAction("List");
        }

        public IActionResult MapUserToRole(UserRole userRole)
        {
            UserProcess user = new UserProcess();
            user.MapUserRole(userRole);
            return View(user);
        }

    }
}

CaseStudyMVC/Views/Accounts/Login.cshtml
@model WebClassLibrary.AuthenticationRequest

@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

<h4>AuthenticationRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CaseStudyMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

@if (Context.Session.GetString("Firstname") != null)
{
    <div class="alert alert-success">
        <div class="display-6"> Name: @Context.Session.GetString("Firstame")</div>
    </div>
}

CaseStudyMVC/Views/Role/Create.cshtml
@model CaseStudy1.DataAccess.Role

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Role</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoleId" class="control-label"></label>
                <input asp-for="RoleId" class="form-control" />
                <span asp-validation-for="RoleId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoleName" class="control-label"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoleDescription" class="control-label"></label>
                <input asp-for="RoleDescription" class="form-control" />
                <span asp-validation-for="RoleDescription" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CaseStudyMVC/Views/Role/Details.cshtml
@model CaseStudy1.DataAccess.Role

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Role</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

CaseStudyMVC/Views/Role/Edit.cshtml
@model CaseStudy1.DataAccess.Role

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Role</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoleId" class="control-label"></label>
                <input asp-for="RoleId" class="form-control" />
                <span asp-validation-for="RoleId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoleName" class="control-label"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoleDescription" class="control-label"></label>
                <input asp-for="RoleDescription" class="form-control" />
                <span asp-validation-for="RoleDescription" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CaseStudyMVC/Views/Role/List.cshtml
@model IEnumerable<CaseStudy1.DataAccess.Role>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RoleId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RoleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RoleDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RoleId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoleDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.RoleId }) |
                @Html.ActionLink("Details", "Details", new { id=item.RoleId }) |
                @Html.ActionLink("Remove", "Remove", new { id=item.RoleId })
            </td>
        </tr>
}
    </tbody>
</table>

CaseStudyMVC/Views/Role/Remove.cshtml
@model CaseStudy1.DataAccess.Role

@{
    ViewData["Title"] = "Remove";
}

<h1>Remove</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Role</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
    
    <form asp-action="Remove">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CaseStudyMVC/Views/Shared/Unauthorized.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="alert alert-danger">
    <div class="display-1">Unauthorized</div>
    <p class="lead text-danger fs-2">
        You are not authorized to access this resource. Please contact your administrator.
    </p>
</div>

CaseStudyMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CaseStudyMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CaseStudyMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CaseStudyMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="List">User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="List">Role</a>
                        </li>
                    </ul>
                </div>
                <div>
                    @if (Context.Session.Keys.Any(c => c.StartsWith("U")))
                    {
                        <span>Welcome, @Context.Session.GetString("Name") !! </span>
                        <a asp-action="Logout" asp-controller="Accounts" class="btn btn-outline-danger">Logout</a>
                    }
                    else
                    {
                        <a asp-action="Login" asp-controller="Accounts" class="btn btn-outline-success">Login</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CaseStudyMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CaseStudyMVC/Views/User/Create.cshtml
@model CaseStudy1.DataAccess.User

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Firstname" class="control-label"></label>
                <input asp-for="Firstname" class="form-control" />
                <span asp-validation-for="Firstname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lastname" class="control-label"></label>
                <input asp-for="Lastname" class="form-control" />
                <span asp-validation-for="Lastname" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CaseStudyMVC/Views/User/Details.cshtml
@model CaseStudy1.DataAccess.User

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Firstname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lastname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserId }) |
    <a asp-action="Index">Back to List</a>
</div>

CaseStudyMVC/Views/User/Edit.cshtml
@model CaseStudy1.DataAccess.User

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Firstname" class="control-label"></label>
                <input asp-for="Firstname" class="form-control" />
                <span asp-validation-for="Firstname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lastname" class="control-label"></label>
                <input asp-for="Lastname" class="form-control" />
                <span asp-validation-for="Lastname" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CaseStudyMVC/Views/User/List.cshtml
@model IEnumerable<CaseStudy1.DataAccess.User>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Firstname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lastname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Firstname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lastname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.UserId }) |
                @Html.ActionLink("Details", "Details", new { id=item.UserId }) |
                @Html.ActionLink("Remove", "Remove", new { id=item.UserId })
            </td>
        </tr>
}
    </tbody>
</table>

CaseStudyMVC/Views/User/MapUserToRole.cshtml
@model CaseStudy1.DataAccess.UserRole

@{
    ViewData["Title"] = "MapUserToRole";
}

<h1>MapUserToRole</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="MapUserToRole">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoleId" class="control-label"></label>
                <input asp-for="RoleId" class="form-control" />
                <span asp-validation-for="RoleId" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CaseStudyMVC/Views/User/Remove.cshtml
@model CaseStudy1.DataAccess.User

@{
    ViewData["Title"] = "Remove";
}

<h1>Remove</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Firstname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lastname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
    
    <form asp-action="Remove">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>